const allCities = [
    "alicante",
    "amalfi",
    "antibes",
    "barcelona",
    "benidorm",
    "cannes",
    "corfu",
    "dubrovnik",
    "faro",
    "ibiza",
    "kotor",
    "lagos",
    "lisbon",
    "malaga",
    "mallorca",
    "marbella",
    "monaco",
    "mykonos",
    "nice",
    "palma",
    "paphos",
    "porto",
    "rimini",
    "santorini",
    "split",
    "st. tropez",
    "tenerife",
    "valencia",
    "vigo",
    "zadar",
    "amsterdam",
    "athens",
    "berlin",
    "bratislava",
    "bruges",
    "budapest",
    "copenhagen",
    "edinburgh",
    "florence",
    "helsinki",
    "istanbul",
    "krakow",
    "ljubljana",
    "madrid",
    "milan",
    "munich",
    "paris",
    "prague",
    "reykjavik",
    "rome",
    "salzburg",
    "seville",
    "stockholm",
    "tallinn",
    "venice",
    "vienna",
    "warsaw",
    "åre",
    "bled",
    "chamonix",
    "cortina d'ampezzo",
    "geiranger",
    "gimmelwald",
    "grindelwald",
    "innsbruck",
    "interlaken",
    "jungfrau",
    "kitzbühel",
    "lake bled",
    "lauterbrunnen",
    "lech",
    "lucerne",
    "mont blanc",
    "nærøyfjord",
    "oberstdorf",
    "plitvice",
    "sankt anton",
    "sölden",
    "st. moritz",
    "tromsø",
    "val d'isère",
    "verbier",
    "zell am see",
    "zermatt",
    "brussels",
    "bucharest",
    "dublin",
    "hamburg",
    "london",
    "naples",
    "oslo",
    "zurich",
    "fuerteventura",
    "lanzarote",
    "leogang",
    "livigno",
    "marseille",
    "saint-jean-de-luz",
    "sestriere",
    "sierra nevada",
    "solden",
    "tignes",
    "torremolinos",
    "turin",
    "zweisimmen"
]

module.exports = allCities;